config/routes.rb
Rails.application.routes.draw do
  # get 'users/my_portfolio'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stock', to: 'stock#serach'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord

  def self.new_lookup(ticker_symbl)
    begin
      client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:pub_key],
      secret_token: Rails.application.credentials.iex_client[:secret_token],
      endpoint: Rails.application.credentials.iex_client[:sand_box]
      )    
      # client.price(ticket_symbl)
      new(ticker: ticker_symbl, name: client.company(ticker_symbl).company_name , last_price: client.price(ticker_symbl))      
    rescue => exception
      return nil
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/stock_controller.rb
class StockController < ApplicationController

  def serach
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock]);
      if @stock
        respond_to do |format|
          format.js {render partial: 'users/result'}
        end
          # render 'users/my_portfolio'      
      else
        respond_to do |format|
          flash.now[:alert] = "Not company foudn with ticker symbol: '#{params[:stock]}'!!!"
          format.js { render partial: 'users/result'}
        end
        
        # redirect_to my_portfolio_path
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Serach can't be 'émpty' strign"
        format.js { render partial: 'users/result'}
      end      
      # redirect_to my_portfolio_path
    end 
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def def index
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_message.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>
<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" aria-disabled="true">Disabled</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/message' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_result.html.erb
<div class="results-block">
    <%= render 'layouts/message' %>
</div>


<% if @stock %>
<div class="card card-header results-block">
  <strong>Ticker:</strong> <%= @stock.ticker %>
  <strong>Company name:</strong> <%= @stock.name %>
  <strong>Price:</strong> <%= @stock.last_price %>    
</div>
<% end %>

app/views/users/_result.js.erb
document.querySelector("#results").innerHTML =  '<%= j render 'users/result.html'%>'

app/views/users/my_portfolio.html.erb
<h1>My portfolio</h1>

<div class="serach-area">
  <h3>Search stocks</h3>
  <%= form_tag  search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control" %>
      </div>
      <div class="col-sm-3 no-left-padding">
        <%= button_tag type: :submit, class: 'btn btn-success' do %>
          <%= fa_icon 'search' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="results">
  <!-- <%= render 'users/result' %> -->
</div>
  

app/views/welcome/index.html.erb
<h1> Welcome to finance-tracker!! </h1>
<%= link_to 'Sign Out', destroy_user_session_path, method: :delete  %>